In [ ]:
## Logistic Regression: Classification algorithm

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("datasnaek/chess")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'chess' dataset.
Path to dataset files: /kaggle/input/chess

In [2]:
!ls $path

games.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(path+"/games.csv")

In [5]:
df.head(5)

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5
1,l1NXvwaE,True,1.504130e+12,1.504130e+12,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4
2,mIICvQHh,True,1.504130e+12,1.504130e+12,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3
3,kWKvrqYL,True,1.504110e+12,1.504110e+12,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3
4,9tXo1AUZ,True,1.504030e+12,1.504030e+12,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5

In [6]:
df.columns

Index(['id', 'rated', 'created_at', 'last_move_at', 'turns', 'victory_status',
       'winner', 'increment_code', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_eco', 'opening_name', 'opening_ply'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              20058 non-null  object
 1   rated           20058 non-null  bool
 2   created_at      20058 non-null  float64
 3   last_move_at    20058 non-null  float64
 4   turns           20058 non-null  int64
 5   victory_status  20058 non-null  object
 6   winner          20058 non-null  object
 7   increment_code  20058 non-null  object
 8   white_id        20058 non-null  object
 9   white_rating    20058 non-null  int64
 10  black_id        20058 non-null  object
 11  black_rating    20058 non-null  int64
 12  moves           20058 non-null  object
 13  opening_eco     20058 non-null  object
 14  opening_name    20058 non-null  object
 15  opening_ply     20058 non-null  int64
dtypes: bool(1), float64(2), int64(4), object(9)
memory usage: 2.3+ MB

In [8]:
X = df[["white_rating", 'black_rating']]
y = df['winner']

In [9]:
X.head(5)

   white_rating  black_rating
0          1500          1191
1          1322          1261
2          1496          1500
3          1439          1454
4          1523          1469

In [10]:
y.head()

0    white
1    black
2    white
3    white
4    white
Name: winner, dtype: object

In [11]:
y.unique()

array(['white', 'black', 'draw'], dtype=object)

In [13]:
df = df[df['winner'].isin(['white', 'black'])].copy()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19108 entries, 0 to 20057
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19108 non-null  object
 1   rated           19108 non-null  bool
 2   created_at      19108 non-null  float64
 3   last_move_at    19108 non-null  float64
 4   turns           19108 non-null  int64
 5   victory_status  19108 non-null  object
 6   winner          19108 non-null  object
 7   increment_code  19108 non-null  object
 8   white_id        19108 non-null  object
 9   white_rating    19108 non-null  int64
 10  black_id        19108 non-null  object
 11  black_rating    19108 non-null  int64
 12  moves           19108 non-null  object
 13  opening_eco     19108 non-null  object
 14  opening_name    19108 non-null  object
 15  opening_ply     19108 non-null  int64
dtypes: bool(1), float64(2), int64(4), object(9)
memory usage: 2.4+ MB

In [15]:
df.head()

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5
1,l1NXvwaE,True,1.504130e+12,1.504130e+12,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4
2,mIICvQHh,True,1.504130e+12,1.504130e+12,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3
3,kWKvrqYL,True,1.504110e+12,1.504110e+12,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3
4,9tXo1AUZ,True,1.504030e+12,1.504030e+12,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5

In [16]:
X = df[["white_rating", 'black_rating']]
y = df['winner']

In [17]:
y = y.map({'white': 0, 'black': 1})

In [18]:
y

0        0
1        1
2        0
3        0
4        0
        ..
20053    0
20054    1
20055    0
20056    0
20057    1
Name: winner, Length: 19108, dtype: int64

In [19]:
y.unique()

array([0, 1])

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [22]:
X_train.shape, X_test.shape

((13375, 2), (5733, 2))

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
model = LogisticRegression()

In [25]:
model.fit(X_train, y_train)

LogisticRegression()

In [26]:
model.coef_, model.intercept_

(array([[-0.00375774,  0.00385921]]), array([-0.22355181]))

In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [29]:
y_pred = model.predict(X_test)

In [30]:
accuracy = accuracy_score(y_test, y_pred)

In [39]:
f"{accuracy*100:.2f}%"

'65.15%'

In [40]:
cm = confusion_matrix(y_test, y_pred)

In [41]:
cm

array([[2137,  910],
       [1088, 1598]])

In [51]:
TN = cm[0, 0]
TP = cm[1, 1]
FN = cm[1, 0]
FP = cm[0, 1]

In [52]:
TP, TN, FP, FN

(np.int64(1598), np.int64(2137), np.int64(910), np.int64(1088))

In [53]:
# precision
precision = TP/(TP+FP)
precision

np.float64(0.6371610845295056)

In [56]:
# recall
recall = TP/(TP+FN)
recall

np.float64(0.5949367088607594)

In [61]:
# Specifity
spec = TN/(TN+FP)
spec

np.float64(0.7013455858221201)

In [59]:
# F1-Score
F1_score = (2 * precision * recall)/(precision+recall)
F1_score

np.float64(0.6153253754331921)